version: "3.9"

services:
  app:
    build: .
    container_name: work_management
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    restart: always

  mongo:
    image: mongo:6.0
    container_name: work_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
